// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

module github.com/jharvey10/test-repo/otel_engine

go 1.25

require (
	go.opentelemetry.io/collector/confmap/provider/envprovider v1.45.0
	go.opentelemetry.io/collector/confmap/provider/fileprovider v1.45.0
	go.opentelemetry.io/collector/confmap/provider/httpprovider v1.45.0
	go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.45.0
	go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.45.0
	github.com/open-telemetry/opentelemetry-collector-contrib/connector/countconnector v0.147.0
	github.com/open-telemetry/opentelemetry-collector-contrib/connector/spanmetricsconnector v0.147.0
	go.opentelemetry.io/collector/connector/forwardconnector v0.147.0
	github.com/jharvey10/test-repo/extension/baseengine v1.32.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/basicauthextension v0.147.0
	go.opentelemetry.io/collector/extension/zpagesextension v0.147.0
	go.opentelemetry.io/collector/receiver/otlpreceiver v0.147.0
	go.opentelemetry.io/collector/exporter/otlphttpexporter v0.147.0
	go.opentelemetry.io/collector/processor/batchprocessor v0.147.0
	go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.147.0
	go.opentelemetry.io/collector/service v0.151.0
	go.opentelemetry.io/collector/otelcol v0.151.0
)

require (
	github.com/knadh/koanf/maps v0.1.1 // indirect
	github.com/knadh/koanf/providers/confmap v0.1.0 // indirect
)
















replace github.com/jharvey10/test-repo => ../
replace github.com/jharvey10/test-repo/syntax => ../syntax
