name: Release Please

on:
  push:
    branches:
      - main
      - 'release/v*'

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token 🔐
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: jharvey10
          repositories: test-repo

      - name: Checkout repository 🛎️
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup Node.js 🏗️
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: tools/release/release-please-runner/.nvmrc
          package-manager-cache: false

      - name: Install dependencies 📦
        working-directory: tools/release/release-please-runner
        run: npm install

      - name: Run release-please 🚀
        working-directory: tools/release/release-please-runner
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          REPO_URL: ${{ github.repository }}
          TARGET_BRANCH: ${{ github.ref_name }}
          CONFIG_FILE: release-please-config.json
          MANIFEST_FILE: .release-please-manifest.json
        run: node index.js
